### ISSUE TITLE
 bert-base-uncased

### ISSUE THREAD

**Issue by wxxxxxq** [SMRE-CV/SMRE#2]
Hello author, when using bert-base-uncased, download bert-base-uncased-vocab .txt, bert-base-uncased-config.json, bert-base-uncased-pytorch_model.bin these three files can be placed in the project directory? I do it this way, run the program to report the following error, look forward to getting your reply, thank you very much!
![image](https://user-images.githubusercontent.com/74249201/178210922-5d248bdc-85d7-4d10-a73b-15b6e9de6fa8.png)

**Comment by SMRE-CV** [comment]
Hmmmmm. ​It seems really weird. I'll update my bert-base-uncased files and maybe you can try it one more time. In general, you can still use bert even if you download a different version. Also, the location of the file doesn't matter much, as long as you can index it to.

**Comment by SMRE-CV** [comment]
Updated.
